<a href="https://colab.research.google.com/github/CatalinaDeras24/datawarehouse-seguros/blob/main/Copia_de_Clientes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/CatalinaDeras24/datawarehouse-seguros.git

In [ ]:
import pandas as pd

In [ ]:
url = "https://raw.githubusercontent.com/CatalinaDeras24/datawarehouse-seguros/refs/heads/main/data/clientes.csv"

In [ ]:
df = pd.read_csv(url)

In [ ]:
display(df.head())

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

Bloque 2 : Exploracion del DATASET

In [ ]:
print("primeras filas del data set")
display(df.head())

primeras filas del data set

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,Jose.Chavez.Perez1@Gmail.Com,Hombre,2011-11-24,Sanmiguel,NAN
1,2,Daniela Rojas Ortiz,Daniela.Rojas.Ortiz2@Seguro.Sv,NaN,NaT,Sta. Ana,NAN
2,3,Ricardo Cruz Flores,Ricardo.Cruz.Flores3@Example.Com,Masculino,NaT,S. Miguel,NAN
3,4,María Pérez Pérez,Maria.Perez.Perez4@Correo.Com,Masculino,NaT,Lalibertad,REGULAR
4,5,Fernanda Chávez Rojas,Fernanda.Chavez.Rojas5@Seguro.Sv,NaN,1945-08-02,San Salvador,PYME

In [ ]:
print("Dimensiones del dataser(filas,columnas)")
print(df.shape)

Dimensiones del dataser(filas,columnas)
(3030, 7)

In [ ]:
print("Columnas del dataset")
print(df.columns)

Columnas del dataset
Index(['id_cliente', 'nombre', 'email', 'genero', 'fecha_nacimiento', 'ciudad',
       'segmento'],
      dtype='object')

In [ ]:
print("Tipo de datos")
print(df.dtypes)

Tipo de datos
id_cliente           int64
nombre              object
email               object
genero              object
fecha_nacimiento    object
ciudad              object
segmento            object
dtype: object

In [ ]:
print("valor nulos por columna")
print(df.isnull().sum())

valor nulos por columna
id_cliente            0
nombre                0
email                 0
genero              595
fecha_nacimiento      0
ciudad                0
segmento            597
dtype: int64

In [ ]:
print("registros duplicados")
print(df.duplicated().sum())

registros duplicados
0

Bloque 3 : Limpieza de datos

In [ ]:
#Eliminar espacios al inicio y al final
for col in df.select_dtypes(include="object").columns :df[col].str.strip()

In [ ]:
#normalizar el nombre
df["nombre"] = df["nombre"].str.title()

In [ ]:
#normalizar el email
df["email"] = df["email"].str.title()

In [ ]:
#normalizar el genero
df["genero"] = df["genero"].str.title()

In [ ]:
#normalizar el ciudad
df["ciudad"] = df["ciudad"].str.title()

In [ ]:
#Convertir fecha de nacimiento a formato fecha
df["fecha_nacimiento"]= pd.to_datetime(df["fecha_nacimiento"], errors="coerce")

In [ ]:
#limpieza de segmento
df['segmento'] = df['segmento'].astype(str)
df['segmento'] = df['segmento'].str.strip()
df['segmento'] = df['segmento'].str.upper()

In [ ]:
for col in df.columns : print(col)

id_cliente
nombre
email
genero
fecha_nacimiento
ciudad
segmento

Bloque 4 : Validacion de datos

In [ ]:
#crear columna para registrar errores
df["motivo_rechazo"]=""

#validar id_cliente
df.loc[df["id_cliente"].isnull(),"motivo_rechazo"]=="id_cliente nula; "

Series([], Name: motivo_rechazo, dtype: bool)